title: Easy and fast Programming guide For C
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tessera example webpage
baseurl: "/easy_and_fast_programming_guide_for_c_language"
url: ""
github_username: itszariep
permalink: /:title

# Build settings
remote_theme: itszariep/tessera

social_links:
  - name: GitHub
    url: https://github.com/itszariep
    icon: github

collections:
  chapters:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      image: /preview.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "ItsZariep"
      image: /preview.jpg
  -
    scope:
      path: ""
      type: "chapters"
    values:
      author: "ItsZariep"
      layout: post
      image: /preview.jpg